# Generated by Django 3.1 on 2021-08-08 11:31

from django.db import migrations


def init_slaves(apps, schema_editor):
    Slave = apps.get_model("master", "Slave")
    slaves = [
        dict(name="KinoRF_bot", series=-1001566824441, movies=-1001303121124),
        dict(
            name="RUSFLIX_BOT",
            series=-1001392439062,
            movies=-1001218346051,
            enabled=False,
        ),
    ]

    for slave in slaves:
        Slave.objects.create(**slave)


class Migration(migrations.Migration):
    dependencies = [
        ("master", "0001_initial"),
    ]

    operations = [migrations.RunPython(init_slaves)]
