# Generated by Django 3.1 on 2021-09-15 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("netflix_bot", "0009_refferal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bulkmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("PRG", "Progress"),
                            ("ERR", "Error"),
                            ("SUC", "Success"),
                        ],
                        default="NEW",
                        max_length=5,
                    ),
                ),
                ("duration", models.TimeField(null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("buttons", models.JSONField()),
                ("content", models.URLField()),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("PHOTO", "Photo"),
                            ("ANIMA", "Animation"),
                            ("VIDEO", "Video"),
                            ("EMPTY", "Empty"),
                        ],
                        default="EMPTY",
                        max_length=5,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SendList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("sended", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("NEW", "New"), ("ERR", "Error"), ("SUC", "Success")],
                        default="NEW",
                        max_length=5,
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bulkmail.bulkmail",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="netflix_bot.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bulkmail",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="bulkmail.message"
            ),
        ),
    ]
