# Generated by Django 3.1 on 2021-06-15 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('netflix_bot', '0009_refferal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulkmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.JSONField()),
                ('status', models.CharField(choices=[('S', 'sended'), ('N', 'new')], default='N', max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sended', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulkmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulkmail.bulkmail')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix_bot.user')),
            ],
        ),
    ]
