# Generated by Django 3.1 on 2022-02-12 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("netflix_bot", "0009_refferal"),
    ]

    operations = [
        migrations.CreateModel(
            name="DjangoBulkmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("customer", models.CharField(max_length=128)),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.CreateModel(
            name="UserTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[("TEST", "test user"), ("ANY", "Any user")],
                        default="ANY",
                        max_length=5,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="netflix_bot.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Envelope",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("NEW", "NEW")], default="NEW", max_length=6
                    ),
                ),
                ("media", models.URLField()),
                ("keyboard", models.JSONField(default=list)),
                (
                    "bulkmail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bulkmail.djangobulkmail",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="netflix_bot.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Конверт",
                "verbose_name_plural": "Конверты",
            },
        ),
        migrations.CreateModel(
            name="DjangoMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("media_link", models.URLField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "bulkmail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bulkmail.djangobulkmail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "db_table": "message",
            },
        ),
        migrations.CreateModel(
            name="DjangoButton",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=64)),
                ("link", models.URLField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bulkmail.djangomessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кнопка",
                "verbose_name_plural": "Кнопки",
                "db_table": "button",
            },
        ),
    ]
