# Generated by Django 3.1 on 2022-02-03 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netflix_bot", "0009_refferal"),
        ("bulkmail", "0001_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="djangobutton",
            options={"verbose_name": "Кнопка", "verbose_name_plural": "Кнопки"},
        ),
        migrations.AlterModelOptions(
            name="djangomessage",
            options={"verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
        migrations.CreateModel(
            name="UserTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[("TEST", "test user"), ("ANY", "Any user")],
                        default="ANY",
                        max_length=5,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="netflix_bot.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DjangoRecipient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="netflix_bot.user",
                    ),
                ),
            ],
        ),
    ]
