# Generated by Django 3.1 on 2021-09-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkmail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32)),
                ('link', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='buttons',
        ),
        migrations.AddField(
            model_name='message',
            name='buttons',
            field=models.ManyToManyField(to='bulkmail.Button'),
        ),
    ]
