# Generated by Django 3.1 on 2021-09-21 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkmail', '0002_auto_20210921_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='buttons',
        ),
        migrations.AddField(
            model_name='button',
            name='message',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='bulkmail.message'),
            preserve_default=False,
        ),
    ]
