# Generated by Django 3.1 on 2022-02-05 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netflix_bot", "0009_refferal"),
        ("bulkmail", "0002_recipient"),
    ]

    operations = [
        migrations.CreateModel(
            name="DjangoBulkmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("customer", models.CharField(max_length=128)),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name="Envelope",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("NEW", "NEW")], default="NEW", max_length=6
                    ),
                ),
                ("media", models.URLField()),
                ("keyboard", models.JSONField(default=[])),
                (
                    "bulkmail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bulkmail.djangobulkmail",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="netflix_bot.user",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DjangoRecipient",
        ),
    ]
