# Generated by Django 3.0.6 on 2020-06-02 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('chat_id', models.IntegerField(unique=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_type', models.CharField(choices=[('SER', 'series'), ('MOV', 'movie')], max_length=3)),
                ('title', models.TextField()),
                ('duration', models.TimeField(null=True)),
                ('country', models.TextField(null=True)),
                ('release', models.DateField(null=True)),
                ('description', models.TextField(null=True)),
                ('genres', models.TextField(null=True)),
                ('mpa_rating', models.TextField(null=True)),
                ('imdb_rating', models.TextField(null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'videos',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.TextField(unique=True)),
                ('message_id', models.IntegerField()),
                ('episode', models.IntegerField()),
                ('season', models.IntegerField()),
                ('lang', models.CharField(max_length=3)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix_bot.Video')),
            ],
        ),
    ]
