# Generated by Django 3.0.6 on 2020-07-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='file_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.TextField(null=True),
        ),
    ]
