# Generated by Django 3.1 on 2020-09-05 13:47

from django.db import migrations, models
def add_genres(apps, schema_editor):
    Genre = apps.get_model("netflix_bot", "Genre")
    all_genres = [
        "аниме",
        "биографический",
        "боевик",
        "вестерн",
        "военный",
        "детектив",
        "детский",
        "документальный",
        "драма",
        "исторический",
        "комедия",
        "концерт",
        "короткометражный",
        "криминал",
        "мелодрама",
        "мистика",
        "музыка",
        "мультфильм",
        "мюзикл",
        "научный",
        "приключения",
        "реалити-шоу",
        "семейный",
        "спорт",
        "ток-шоу",
        "триллер",
        "ужасы",
        "фантастика",
        "фильм-нуар",
        "фэнтези",
    ]

    for genre in all_genres:
        Genre.objects.create(name=genre)



class Migration(migrations.Migration):

    dependencies = [
        ('netflix_bot', '0004_split_ru_eng_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.AddField(
            model_name='series',
            name='genre',
            field=models.ManyToManyField(to='netflix_bot.Genre'),
        ),
        migrations.RunPython(add_genres)
    ]
