# Generated by Django 3.1 on 2020-11-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netflix_bot", "0006_add_movies"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="authorize",
            field=models.BooleanField(default=True),
        ),
    ]
