# Generated by Django 3.1 on 2021-01-29 14:42

from django.db import migrations, models


def _fill(qs):
    for series in qs:
        series.title_ru_upper = series.title_ru.upper()
        series.save()


def fill_title_ru_upper_series(apps, schema_editor):
    Series = apps.get_model("netflix_bot", "Series")
    all_series = Series.objects.all()
    _fill(all_series)


def fill_title_ru_upper_movie(apps, schema_editor):
    Movie = apps.get_model("netflix_bot", "Movie")
    all_movies = Movie.objects.all()
    _fill(all_movies)


class Migration(migrations.Migration):

    dependencies = [
        ("netflix_bot", "0007_user_authorize"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="title_ru_upper",
            field=models.TextField(default="<DJANGO.DB.MODELS.FIELDS.CHARFIELD>"),
        ),
        migrations.AddField(
            model_name="series",
            name="title_ru_upper",
            field=models.TextField(default="<DJANGO.DB.MODELS.FIELDS.TEXTFIELD>"),
        ),
        migrations.RunPython(fill_title_ru_upper_movie),
        migrations.RunPython(fill_title_ru_upper_series),
    ]
